### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Haidong-Kang** [Zasder3/Latent-Neural-Differential-Equations-for-Video-Generation#3]
can you provide README for us on how to use it?

**Comment by Zasder3** [comment]
Sorry for the wait I'll see if I can get to that this week! I don't think I'll be refactoring any code simply just adding a how-to style README.md.

**Comment by neerajanand321** [comment]
Hi
If possible please update the readme on how to use it.

**Comment by Zasder3** [comment]
Just updated it with some help. Please give feedback for questions not yet sufficiently answered!
